service:
  name: kaskadi-update-amz-stocks-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  apiGateway:
    restApiId: !ImportValue KaskadiStocksRestAPIGatewayId
    restApiRootResourceId: !ImportValue KaskadiStocksRestAPIGatewayRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: 'arn:aws:lambda:eu-central-1:374163881813:function:kaskadi-set-stocks-lambda' # not using export/import logic to avoid coupling of stack which could cause troubles with deployment in that case

layers:
  KaskadiStockUpdate:
    path: layer
    name: ${self:service.name}-layer
    description: Layer for ${self:service.name}
    compatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
    licenseInfo: MIT

functions:
  KaskadiStockUpdate:
    handler: kaskadi-update-amz-stocks-lambda.handler
    name: ${self:service.name}
    layers:
      - { Ref: KaskadiStockUpdateLambdaLayer }
    package:
      exclude:
        - '**/**'
      include:
        - 'kaskadi-update-amz-stocks-lambda.js'
        - 'marketplaces.js'
    environment:
      ES_ID: ${env:ES_ID}
      ES_SECRET: ${env:ES_SECRET}
      ES_ENDPOINT: ${env:ES_ENDPOINT}
      ACCESS_KEY: ${env:AWS_ACCESS_KEY}
      SELLER_ID: ${env:SELLER_ID}
      MWS_AUTH_TOKEN: ${env:MWS_AUTH_TOKEN}
    timeout: 120
    events:
      - http:
          method: get
          path: amz/update
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !ImportValue KaskadiStocksCognitoAuthorizerId
      - schedule:
          rate: cron(0 7 ? * * *) # runs every day at 7:00AM
          enabled: true
